version: "3.7"

services:
  web:
    image: "eu.gcr.io/lorenzorivosecchi/clam_web:production"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - web-data:/myapp/public
    depends_on:
      - db
    environment:
      # Remember to append the stack prefix to the postgres host
      POSTGRES_HOST: clam_production_db
    deploy:
      labels:
        # Explicitly tell Traefik to expose this container
        - "traefik.enable=true"
        # Get the routes from http
        - "traefik.http.routers.clam_production_web.rule=Host(`clam.life`, `www.clam.life`)"
        - "traefik.http.routers.clam_production_web.entrypoints=web"
        # Redirect these routes to https
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.routers.clam_production_web.middlewares=redirect-to-https"
        # Get the routes from https
        - "traefik.http.routers.clam_production_web-secure.rule=Host(`clam.life`, `www.clam.life`)"
        - "traefik.http.routers.clam_production_web-secure.entrypoints=websecure"
        - "traefik.http.routers.clam_production_web-secure.tls=true"
        - "traefik.http.routers.clam_production_web-secure.tls.certresolver=myresolver"
        # Restrict access with basic auth
        #   To create user:password pair, it's possible to use this command:
        #   echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
        # - "traefik.http.middlewares.clam-production-auth.basicauth.users=cl20:$$apr1$$62oHG6o0$$0kR0X0dxMbAmUmcKNLrUF."
        # - "traefik.http.routers.clam_production_web-secure.middlewares=clam-production-auth"
        # Specify the port to use for communication
        - "traefik.http.services.clam_production_web.loadbalancer.server.port=3000"
    networks:
      - lorenzo-proxy-net

  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backups:/backups
    secrets:
      - db-password
    networks:
      - lorenzo-proxy-net

networks:
  lorenzo-proxy-net:
    external: true

volumes:
  db-data:
  web-data:

secrets:
  db-password:
    file: ./secrets/db-password.txt
